---
- name: Start sensor loop
  become: true
  service:
    name: sensor-loop
    state: started
    enabled: true

- name: Restart sensor loop
  become: true
  service:
    name: sensor-loop
    state: restarted

- name: Start sensor app
  become: true
  service:
    name: sensor-app
    state: started
    enabled: true

- name: Restart sensor app
  become: true
  service:
    name: sensor-app
    state: restarted

- name: Restart nginx
  become: true
  service:
    name: nginx
    state: restarted

- name: Reload systemd
  become: true
  systemd:
    daemon_reload: true

