---
- name: Update application
  copy:
    src: "../app/{{ item }}"
    dest: /home/pi/app/
  with_items:
    - requirements.txt
    - hello.py
    - main.py
    - create-database.sql
    - reset-db.sh

