---
- name: Update app
  hosts: all
  gather_facts: false

  tasks:
    - name: Update application
      copy:
        src: "../app/{{ item }}"
        dest: /home/pi/app/
      with_items:
        - requirements.txt
        - web.py
        - web.ini
        - main.py
        - create-database.sql
        - reset-db.sh
        - wsgi.py
      notify:
        - Restart sensor loop
