---
- name: Update app
  hosts: all
  gather_facts: false
  vars_files:
    - vars.yml

  handlers:
    - import_tasks: roles/application/handlers/main.yml

  tasks:
    - name: Update application
      copy:
        src: "../app/{{ item }}"
        dest: "{{ app_root }}/"
      with_items: "{{ app_files }}"
      notify:
        - Restart sensor loop
        - Restart sensor app
